spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/student_tracker"
    username: springstudent
    password: springstudent
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: warn
    org:
      hibernate:
        sql: debug
        orm:
          jdbc:
            bind: trace